version: "2"

run:
  timeout: 5m
  tests: true

linters:
  default: none
  enable:
    - bodyclose
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused

  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck
          - unused

issues:
  exclude-default: true
